# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  oxauth:
    image: gluufederation/oxauth:4.3.0_dev
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_COUCHBASE_BUCKET_PREFIX=${COUCHBASE_BUCKET_PREFIX}
      - GLUU_DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
      - GLUU_JACKRABBIT_URL=http://jackrabbit:8080
      - GLUU_JACKRABBIT_ADMIN_ID=${JACKRABBIT_USER}
      - GLUU_JACKRABBIT_ADMIN_PASSWORD_FILE=/etc/gluu/conf/jackrabbit_admin_password
      - GLUU_SQL_DB_DIALECT=${SQL_DB_DIALECT}
      - GLUU_SQL_DB_NAME=${SQL_DB_NAME}
      - GLUU_SQL_DB_HOST=${SQL_DB_HOST}
      - GLUU_SQL_DB_PORT=${SQL_DB_PORT}
      - GLUU_SQL_DB_USER=${SQL_DB_USER}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GLUU_GOOGLE_SPANNER_INSTANCE_ID=${GOOGLE_SPANNER_INSTANCE_ID}
      - GLUU_GOOGLE_SPANNER_DATABASE_ID=${GOOGLE_SPANNER_DATABASE_ID}
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxauth
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
      - ./jackrabbit_admin_password:/etc/gluu/conf/jackrabbit_admin_password
      - ./google-credentials.json:/etc/gluu/conf/google-credentials.json
      - ./sql_password:/etc/gluu/conf/sql_password
    mem_limit: 1536M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxauth"
      - "SERVICE_8080_CHECK_HTTP=/oxauth/restv1/health-check"
      - "SERVICE_8080_CHECK_INTERVAL=30s"
      - "SERVICE_8080_CHECK_TIMEOUT=30s"
      - "APP_NAME=oxauth"
