# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  mysql:
    image: postgres:12
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - POSTGRES_ROOT_PASSWORD_FILE=/run/secrets/sql_root_password
      - POSTGRES_USER=${SQL_DB_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/sql_password
      - POSTGRES_DB=${SQL_DB_NAME}
    volumes:
      - ./sql_root_password:/run/secrets/sql_root_password
      - ./sql_password:/run/secrets/sql_password
      - ./volumes/postgresql-12:/var/lib/postgresql/data
    container_name: postgresql
    # cap_add:
    #   - SYS_NICE
