# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  jackrabbit:
    image: gluufederation/jackrabbit:4.1.1_02
    container_name: jackrabbit
    volumes:
      - ./volumes/jackrabbit/repository:/opt/jackrabbit/repository
      - ./volumes/jackrabbit/version:/opt/jackrabbit/version
      - ./volumes/jackrabbit/workspaces:/opt/jackrabbit/workspaces
    labels:
      - "SERVICE_IGNORE=yes"
    restart: unless-stopped
