# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  fido2:
    image: gluufederation/fido2:4.2.2_02
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_COUCHBASE_BUCKET_PREFIX=${COUCHBASE_BUCKET_PREFIX}
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: fido2
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
    mem_limit: 1024M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=fido2"
      - "SERVICE_8080_CHECK_HTTP=/fido2/restv1/fido2/configuration"
      - "SERVICE_8080_CHECK_INTERVAL=30s"
      - "SERVICE_8080_CHECK_TIMEOUT=30s"
