# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  ldap:
    image: gluufederation/opendj:4.5.5-1
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      # the value must match service name `ldap` because other containers
      # use this value as LDAP hostname
      - GLUU_CERT_ALT_NAME=ldap
      - GLUU_LDAP_ADVERTISE_ADDR=
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
    container_name: ldap
    hostname: ldap
    volumes:
      - ./volumes/opendj/config:/opt/opendj/config
      - ./volumes/opendj/ldif:/opt/opendj/ldif
      - ./volumes/opendj/logs:/opt/opendj/logs
      - ./volumes/opendj/db:/opt/opendj/db
      - ./volumes/opendj/backup:/opt/opendj/bak
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      # - ./101-ox.ldif:/opt/opendj/config/schema/101-ox.ldif
    restart: unless-stopped
    mem_limit: 2048M
    user: "0"
    healthcheck:
      test: python3 /app/scripts/healthcheck.py
      interval: 30s
      timeout: 5s
      retries: 20
      start_period: 30s
    labels:
      - "autoheal=true"
