# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  oxshibboleth:
    image: gluufederation/oxshibboleth:4.2.0_01
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_OXTRUST_BACKEND=oxtrust:8080
      - GLUU_JCA_URL=http://jackrabbit:8080
      - GLUU_DOCUMENT_STORE_TYPE=${DOCUMENT_STORE_TYPE}
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    container_name: oxshibboleth
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
    mem_limit: 1024M
    restart: unless-stopped
    labels:
      - "SERVICE_NAME=oxshibboleth"
      - "SERVICE_8086_CHECK_HTTP=/idp"
      - "SERVICE_8086_CHECK_INTERVAL=30s"
      - "SERVICE_8086_CHECK_TIMEOUT=30s"
      - "APP_NAME=oxshibboleth"
