# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  cr_rotate:
    image: gluufederation/cr-rotate:4.5.3-1
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_CR_ROTATION_CHECK=60
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_COUCHBASE_BUCKET_PREFIX=${COUCHBASE_BUCKET_PREFIX}
      - GLUU_SQL_DB_DIALECT=${SQL_DB_DIALECT}
      - GLUU_SQL_DB_NAME=${SQL_DB_NAME}
      - GLUU_SQL_DB_HOST=${SQL_DB_HOST}
      - GLUU_SQL_DB_PORT=${SQL_DB_PORT}
      - GLUU_SQL_DB_USER=${SQL_DB_USER}
      - GLUU_SQL_DB_SCHEMA=${SQL_DB_SCHEMA}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GLUU_GOOGLE_SPANNER_INSTANCE_ID=${GOOGLE_SPANNER_INSTANCE_ID}
      - GLUU_GOOGLE_SPANNER_DATABASE_ID=${GOOGLE_SPANNER_DATABASE_ID}
      - SPANNER_EMULATOR_HOST=${SPANNER_EMULATOR_HOST}
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - /var/run/docker.sock:/var/run/docker.sock
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
      - ./google-credentials.json:/etc/gluu/conf/google-credentials.json
      - ./sql_password:/etc/gluu/conf/sql_password
    container_name: cr-rotate
    restart: unless-stopped
    mem_limit: 512M
    user: "0"
