# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  redis:
    image: redis:alpine
    # run cluster-enabled redis-server
    # command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --appendonly yes --cluster-node-timeout 5000
    container_name: redis
    restart: unless-stopped
    mem_limit: 512M
