# use v2.x API to allow `mem_limit` option
version: "2.4"

services:
  oxd_server:
    image: gluufederation/oxd-server:4.2.2_03
    environment:
      - GLUU_CONFIG_CONSUL_HOST=consul
      - GLUU_SECRET_VAULT_HOST=vault
      - GLUU_PERSISTENCE_TYPE=${PERSISTENCE_TYPE}
      - GLUU_PERSISTENCE_LDAP_MAPPING=${PERSISTENCE_LDAP_MAPPING}
      - GLUU_LDAP_URL=ldap:1636
      - GLUU_COUCHBASE_URL=${COUCHBASE_URL}
      - GLUU_COUCHBASE_USER=${COUCHBASE_USER}
      - GLUU_COUCHBASE_BUCKET_PREFIX=${COUCHBASE_BUCKET_PREFIX}
      - GLUU_OXD_APPLICATION_CERT_CN=oxd_server
      - GLUU_OXD_ADMIN_CERT_CN=oxd_server
    container_name: oxd-server
    restart: unless-stopped
    mem_limit: 1024M
    extra_hosts:
      - "${DOMAIN}:${HOST_IP}"
    volumes:
      - ./vault_role_id.txt:/etc/certs/vault_role_id
      - ./vault_secret_id.txt:/etc/certs/vault_secret_id
      - ./couchbase.crt:/etc/certs/couchbase.crt
      - ./couchbase_password:/etc/gluu/conf/couchbase_password
